// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>
#include <utility/wifi_drv.h>
#include "DHT.h"
#include <ArduinoHttpClient.h>

const char SSID[]         = SECRET_SSID;    // Network SSID (name)
const char PASS[]         = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)

unsigned long CH_ID        = (unsigned long)(SECRET_CH_ID);			// channel ID securly stored in Arduino Cloud
const char WRITE_APIKEY[] = SECRET_WRITE_APIKEY;                // channel APIKey securly stored in Arduino Cloud

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
